[build]
  publish = "."
  functions = "netlify/functions"
  command = "echo 'Static site'"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[context.production]
  environment = { NODE_VERSION = "18", GOOGLE_SHEET_URL = "https://script.google.com/macros/s/AKfycbyV5epXHNj8tG9CpUbvXHt8AeVRbepZcuCmeqbUn0AxDIJppvZyasqwR71nn6hXLs4D/exec" }

[context.deploy-preview]
  environment = { NODE_VERSION = "18", GOOGLE_SHEET_URL = "https://script.google.com/macros/s/AKfycbyV5epXHNj8tG9CpUbvXHt8AeVRbepZcuCmeqbUn0AxDIJppvZyasqwR71nn6hXLs4D/exec" }

[context.branch-deploy]
  environment = { NODE_VERSION = "18", GOOGLE_SHEET_URL = "https://script.google.com/macros/s/AKfycbyV5epXHNj8tG9CpUbvXHt8AeVRbepZcuCmeqbUn0AxDIJppvZyasqwR71nn6hXLs4D/exec" }
